#!/bin/bash
###############################################################
###### BASIC SETTINGS- JUST REPLACE WITH YOUR INFORMATION #####
###############################################################
StatsInterval=1 			        #1 for Dynamic Benchmarking Of Devices, 1000 For Static (Benchmarks once, then doesn't do it again)
UserName=MaynardVII				#Username For Pools Which Require It. Go to pool and make one. (MiningPoolHub)
WorkerName=Rig1				        #Workername For Pools Which Require It. Go to pool and make one. (MiningPoolHub)
RigName=MMHash				        #Personal Nickname Of Your Mining Rig (for tracking purposes)
Currency=USD				        #Fiat Currency You Prefer
Passwordcurrency=BTC		 		#Coin You Want To Exchange To For Pools Which Offer Mining Coin Exchange...See Your Mining Pool For More Information
CoinExchange=BTC    	         		#Excange Quote From CryptoExchange. Keep PasswordCurrency Symbol, unless coin symbol on cryptoexchange is different!
Interval=240				        #Seconds Miner Runs Before Switching (5 minutes is reccommended)
Delay=1					        #Delay Before Miner Switches (Leave alone- EXPERT/DEBUG MODE ONLY!)
Wallet=1DRxiWx6yuZfN9hrEJa3BDXWVJ9yyJU36i	#Your Wallet Address
Location=US	                 		#Your Country
PoolName=zergpool,mph		 		#Name of Pool You Wish To Mine In (See "Pools" dir To See Available Pools ex: zergpool,zpool,ahashpool)
Type=CPU,NVIDIA                 		#Devices You Are Mining With (NVIDIA,CPU,AMD) (CAREFULL COMBINING DEVICES!!
Algorithm=Yescrypt,Yescryptr16,Neoscrypt,Allium,HMQ1725,Keccak,Lyra2z,Keccakc,Xevan,X16r,Hsr,X17,Blake2s,lyra2v2,Bitcore,X16s,Phi,Timetravel,Skunk,Tribus,Sib,Skein,Groestl,Nist5,c11,Equihash	      	   		     #Algos To Mine
Donate=1                                        #Percent You Wish To Donate For Development: 50 maximum (1 is 1% Total)
Proxy='""'                                      #Proxy Address (If You Are Using Proxy)
###########################################################################
#### ADVANCED OPTIONS (DO NOT USE UNLESS YOU KNOW WHAT YOU ARE DOING!) ####
###########################################################################
#Type=NVIDIA1,NVIDIA2,NVIDIA3,NVIDIA4,NVIDIA5,NVIDIA6,NVIDIA7,NVIDIA8                         # Place # in front of above 'Type', and use this one instead.
###
#GPUDevices1='"GTX1070#1"'   # 0,1,2 or GTX1070#1, GTX1080ti#2, etc.
#EWBFDevices1='"0"'		    #0 1 2 No Commas			
#Wallet1=RKirUe978mBoa2MRWqeMGqDzVAKTafKh8H
#PasswordCurrency1=RVN
###
#GPUDevices2='"GTX1070#2"'
#EWBFDevices2='"2"'
#Wallet2=RKirUe978mBoa2MRWqeMGqDzVAKTafKh8H
#PasswordCurrency2=RVN
###
#GPUDevices3='"GTX1070#3"'
#EWBFDevices3='"6"'
#Wallet3=RKirUe978mBoa2MRWqeMGqDzVAKTafKh8H
#PasswordCurrency3=RVN
###
#GPUDevices4='"GTX1050ti#1,GTX1050ti#2,GTX1050ti#5,GTX1050#6"'
#EWBFDevices4='"1 3 4 5"'
#Wallet4=RKirUe978mBoa2MRWqeMGqDzVAKTafKh8H
#PasswordCurrency4=RVN
###
#GPUDevices5='"GTX1050ti#3,GTX1050ti#4,GTX1050ti#7,GTX1050ti#8"'
#EWBFDevices5='"7 8 9 10"'
#Wallet5=RKirUe978mBoa2MRWqeMGqDzVAKTafKh8H
#PasswordCurrency5=RVN
###
#GPUDevices6='"GTX1050ti#5,GTX1050ti#6"'
#EWBFDevices6=
#Wallet6=RKirUe978mBoa2MRWqeMGqDzVAKTafKh8H
#PasswordCurrency6=RVN
###
#GPUDevices7='"GTX1050ti#7"'
#EWBFDevices7=
#Wallet7=RKirUe978mBoa2MRWqeMGqDzVAKTafKh8H
#PasswordCurrency7=RVN
###
#GPUDevices8='"GTX1050ti#8"'
#EWBFDevices8=
#Wallet8=RKirUe978mBoa2MRWqeMGqDzVAKTafKh8H
#PasswordCurrency8=RVN
################################################
####### FLAG COMMANDS ##### DO NOT TOUCH! ######
################################################
a=$StatsInterval
b=$UserName
c=$WorkerName
d=$RigName
e=($Currency)
f=($Passwordcurrency)
g=$Interval
h=$Delay
i=$Wallet
j=$Location
k=$PoolName
l=$Type
m=$Algorithm
n=$Donate
o=$Proxy
p=$CoinExchange
s=$GPUDevices1
u=$Wallet1
v=$PasswordCurrency1
x=$GPUDevices2
y=$Wallet2
z=$PasswordCurrency2
aa=$GPUDevices3
bb=$Wallet3
cc=$PasswordCurrency3
dd=$GPUDevices4
ee=$Wallet4
ff=$PasswordCurrency4
gg=$GPUDevices5
hh=$Wallet5
ii=$PasswordCurrency5
NN=$GPUDevices6
PP=$Wallet6
QQ=$PasswordCurrency6
RR=$GPUDevices7
TT=$Wallet7
UU=$PasswordCurrency7
VV=$GPUDevices8
XX=$Wallet8
YY=$PasswordCurrency8
aaa=$EWBFDevices1
bbb=$EWBFDevices2
ccc=$EWBFDevices3
ddd=$EWBFDevices4
eee=$EWBFDevices5
fff=$EWBFDevices6
ggg=$EWBFDevices7
hhh=$EWBFDevices8
#############################################################################################
#### COMMANDS- SEE README ON HOW TO EDIT FOR ADVANCED SETTINGS! OTHERWISE, DO NOT TOUCH! ####
#############################################################################################
pwsh -command "&.\MM.Hash.ps1 -StatsInterval $a -Username $b -WorkerName $c -RigName $d -Currency $e -Passwordcurrency $f -Interval $g -Delay $h -Wallet $i -Location $j -Poolname $k -Type $l -Algorithm $m -Donate $n -Proxy $o -CoinExchange $p" #-GPUDevices1 $s -EWBFDevices1 $aaa -Wallet1 $u -PasswordCurrency1 $v -GPUDevices2 $x -EWBFDevices2 $bbb -Wallet2 $y -PasswordCurrency2 $z -GPUDevices3 $aa EWBFDevices3 $ccc -Wallet3 $bb -PasswordCurrency3 $cc -GPUDevices4 $dd -EWBFDevices4 $ddd -Wallet4 $ee -PasswordCurrency4 $ff -GPUDevices5 $gg -EWBFDevices5 $eee  -Wallet5 $hh -PasswordCurrency5 $ii -GPUDevices6 $NN -EWBFDevices6 $fff -Wallet6 $PP -PasswordCurrency6 $QQ -GPUDevices7 $RR -EWBFDevices7 $ggg -Wallet7 $TT -PasswordCurrency7 $UU -GPUDevices8 $VV -EWBFDevices8 $hhh -Wallet8 $XX -PasswordCurrency8 $YY"
#
#
#
#
#############################################################
#### Type 'bash StartMM' in terminal AND YOU ARE MINING! ####
#############################################################
